export {
  PITCH_CLASS_SHARPS,
  PITCH_CLASS_FLATS,
  MAJOR_SCALE_SEMITONES,
  MINOR_SCALE_SEMITONES,
  HARMONIC_MINOR_SEMITONES,
  MELODIC_MINOR_SEMITONES,
  MAJOR_KEY_SEVENTH_QUALITIES,
  MINOR_KEY_SEVENTH_QUALITIES,
  MAJOR_KEY_FUNCTIONS,
  MINOR_KEY_FUNCTIONS,
  CHORD_QUALITY_INTERVALS,
  ROMAN_NUMERALS,
  CHORD_SCALES,
  noteToPitchClass,
  pitchClassToNote,
  intervalBetween,
  transposePitchClass,
  chordToPitchClasses,
  isSamePitchClass,
  minSemitoneDistance,
  scaleToPitchClasses,
  isPitchClassInSet,
  getScaleDegree,
  permutations,
} from './constants.js';

export type {
  PitchClass,
  Note,
  ChordQuality,
  Mode,
  Key,
  Extension,
  Alteration,
  AddedTone,
  Suspension,
  ParsedChord,
  HarmonicFunction,
  RomanNumeralAnalysis,
  ChordScaleAssignment,
  ChordVariant,
  SubstitutionCategory,
  GuideToneMatch,
  MatrixColumn,
  VoiceLeadingDistance,
  VoiceLeadingPath,
  VoiceLeadingMatrix,
} from './types.js';
